In [1]:
print("hello0 world!")

hello0 world!


In [2]:
pip install beautifulsoup4

Note: you may need to restart the kernel to use updated packages.


In [3]:
from numpy import random
import numpy as np#importing numpy

In [4]:
a = np.array([1,2,4,6,8,9])

In [5]:
print(a)

[1 2 4 6 8 9]


In [6]:
type(a)

numpy.ndarray

In [7]:
arr=np.array([[1,4,7,2],[3,5,6,9]])

In [8]:
#another way to do 2 dim array
list1=[1,3,5,7]
list2=[2,4,6,8]
list3=[2,3,5,7]
a=np.array([list1,list2,list3])

In [9]:
print(arr.ndim)

2


In [10]:
arr

array([[1, 4, 7, 2],
       [3, 5, 6, 9]])

In [11]:
a

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [2, 3, 5, 7]])

In [12]:
arr.shape

(2, 4)

In [13]:
a.shape

(3, 4)

In [14]:
a.reshape(4,3)

array([[1, 3, 5],
       [7, 2, 4],
       [6, 8, 2],
       [3, 5, 7]])

In [15]:
a[1:,1:3]

array([[4, 6],
       [3, 5]])

In [16]:
arr3=np.array([[[1,3,5,7],[2,4,6,8]],[[2,3,5,7],[2,3,4,5]]])

In [17]:
#using shape it tells [how many 2dimensions, how many 1dimensions, number of element in an array]
arr3.shape

(2, 2, 4)

In [18]:
arr3.ndim

3

In [19]:
arr3

array([[[1, 3, 5, 7],
        [2, 4, 6, 8]],

       [[2, 3, 5, 7],
        [2, 3, 4, 5]]])

In [20]:
arr3[0,1,1]

4

In [21]:
#conditions in array
val=2
arr>2

array([[False,  True,  True, False],
       [ True,  True,  True,  True]])

In [22]:
#show how many value greater than 2
arr[arr>2]

array([4, 7, 3, 5, 6, 9])

In [23]:
b=np.arange(0,100)  # arange are called iterators they do not return values 

In [24]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
b=random.randint(0,100,size=(2,5))

In [26]:
b

array([[69,  9, 39, 11, 14],
       [81, 86, 50, 20, 35]])

In [27]:
import pandas as pd

data = pd.read_csv('data(1).csv')

print(data)


     Weight  Cholesterol  Gender
0       102          111       1
1       115          135       1
2       115          136       1
3       140          167       0
4       130          158       1
..      ...          ...     ...
542     172          207       1
543     129          157       1
544     107          115       1
545     117          147       1
546     148          176       1

[547 rows x 3 columns]


In [28]:
from sklearn.cluster import KMeans
cls = KMeans(n_clusters=4 )
cls.fit(data)

KMeans(n_clusters=4)

In [29]:
from collections import Counter
Counter(cls.labels_)

Counter({0: 140, 3: 135, 2: 154, 1: 118})

In [38]:
import numpy as np
print('Attribute          cluster_0      cluster_1       cluster_2       cluster_3')
for col, center in zip(data.columns,cls.cluster_centers_.T):
    c = '|'.join(f'{i:^15f}' for i in center)
    print(f'{col :15s}|{c}|')

Attribute          cluster_0      cluster_1       cluster_2       cluster_3
Weight         |  106.850000   |  152.093220   |  184.318182   |  127.725926   |
Cholesterol    |  119.535714   |  185.906780   |  218.915584   |  154.385185   |
Gender         |   0.542857    |   0.440678    |   0.590909    |   0.459259    |
